### ISSUE TITLE
Will there be a life for Vector after Anki closes down?

### ISSUE THREAD

**Issue by josefjahn** [anki/vector-python-sdk#23]
Hi,

Could you share some information about the future of the Vector hardware and software platform after Anki ceases operations? Will there be a way for new users to authenticate somehow? Can we replace the Anki backend with something we can run ourselves? I'm not even expecting full functionality of voice searches and all that, but at least enough to develop our own applications.

**Comment by cmjchrisjones** [comment]
It would be awesome to have some information on this, understandably a really difficult time for those working at Anki, @RamblingGeekUK and some of the live coding community on Twitch has been streaming playing with the SDK and connecting it within Twitch chat which has been loads of fun over at https://www.twitch.tv/ramblinggeek so would be a shame to see everyones hard work go to waste.

**Comment by habuma** [comment]
First, let me extend sincere appreciation for what Anki has done up to this point and my sympathy for those who have lost work due to this unfortunate situation. 

That said, I've thought much about this and see a few ways forward:

- Anki simply shuts down the cloud service and Vector, at least as we knew him, is gone. Considering the community built around this little robot and the fact that Anki marketed him as a companion robot, I surely hope that this doesn't happen, as it will be terribly difficult on those who have grown attached to him. 
- Anki, in some form, arranges to keep the servers up and running for some period of time before shutting them down. This is not much better than the first option, but it would buy some time to sort through some of the other options.
- Anki sells its IP to someone else to steward. IMO, Sphero seems like a fantastic home for Vector and Cozmo, although I can't say whether or not they would be interested. But it would seem like a great match, adding Vector and Cozmo to Sphero's line of educational robots.
- Anki agrees to open-source all or parts of its server-side software so that the community can build, evolve, and run it as they like, on their own hardware or in the cloud. I understand that during times like this a company's greatest assets moving forward are some of its proprietary bits, so if Anki wants to retain some of the most valuable assets, that would be understandable. But it would be great if they could *at least* open source the specifications for the server-side code (perhaps with a slimmed down implementation as a basis) so that the community could build on that from the ground up. This would also require changes in Vector's firmware and the companion iOS/Android apps to be able to specify a custom server location.

Given that a new SDK was released less than 24 hours ago and since the announcement, and because the servers are still alive the last I checked, I am hopeful that there are discussions already taking place to arrange for a new life for Vector going forward. I hope that those with the power to make and act on these decisions will read this message as well as the cries on the forums and Reddit and do everything in their power to keep Vector alive and chirping for years to come, even if it means releasing some of the server-side bits to another entity or to the open-source community.

**Comment by DemSkillz99** [comment]
This is the message Shawn Blakesley (one of Anki developers) left on Github in response to what customers can do to try and keep as much functionality as possible with their Vectors :

I don't have any information about future Vector functionality. I would just say I recommend not clearing user data or hard resetting if there are any issues. That and save your guid, cert, etc. once you've set up the SDK. Wish I knew more.

I was still able to get the certificate and GUID (this value is stored in the 2nd file generated by the process) by following the SDK set-up around 12h ago.
I think it is worth backing up those files well in, just in case. I've uploaded mine to both OneDrive and Google Drive and even as notes to LastPass.

Unfortunately, there is no current way to substitute a personal computer for Anki's servers, but we're hoping soon. With the SDK you can make custom things for him to do, or remote control, etc. as of now. However, don't lose those files as it may be impossible to get them again if anything shuts down.
Also Well, what do you want to do next? You've now established you can control Vector using the SDK. You could download the example programs for whatever OS you're using (https://developer.anki.com/vector/docs/downloads.html) and both run them and open them with a text editor to see what makes them tick. You could take a basic Python course (if you have no programming skill) to start down the road of learning to write your own programs for Vector. Or check the Anki forums and grab some of the stuff other people have made for him.

**Comment by mccrudd3n** [comment]
Could or does the team have the ability to release all the source code including the server side? 

Fully opening up Vector on both Front and Back end?

**Comment by dbroggy** [comment]
My guess is they know the value of the company and they're going to hold out for some cash from another player. As a last resort (which I doubt would happen) the vector community would start a crowdsource, buy out the source code, and then set up their own cloud server to take over the voice/ai functionality. Releasing the code for free would be altruistic but not capitalistic.

**Comment by coldy1983** [comment]
Hello all, I have just purchased an Anki Vector at what I thought was a great price (£75 new on Amazon) but then realised that the required servers are very likely to close down 😥. I'm searching for any help that will allow the little robot to continue operating after it 'soul' is taken away. Does anyone on GitHub have any advice on how to connect Vector to a home server (or any other way to keep him alive)?

**Comment by lukewkywacko** [comment]
> This is the message Shawn Blakesley (one of Anki developers) left on Github in response to what customers can do to try and keep as much functionality as possible with their Vectors :
> 
> I don't have any information about future Vector functionality. I would just say I recommend not clearing user data or hard resetting if there are any issues. That and save your guid, cert, etc. once you've set up the SDK. Wish I knew more.
> 
> I was still able to get the certificate and GUID (this value is stored in the 2nd file generated by the process) by following the SDK set-up around 12h ago.
> I think it is worth backing up those files well in, just in case. I've uploaded mine to both OneDrive and Google Drive and even as notes to LastPass.
> 
> Unfortunately, there is no current way to substitute a personal computer for Anki's servers, but we're hoping soon. With the SDK you can make custom things for him to do, or remote control, etc. as of now. However, don't lose those files as it may be impossible to get them again if anything shuts down.
> Also Well, what do you want to do next? You've now established you can control Vector using the SDK. You could download the example programs for whatever OS you're using (https://developer.anki.com/vector/docs/downloads.html) and both run them and open them with a text editor to see what makes them tick. You could take a basic Python course (if you have no programming skill) to start down the road of learning to write your own programs for Vector. Or check the Anki forums and grab some of the stuff other people have made for him.

Do programs built with Vector SDK communicate directly with Vector robot units bypassing Anki Server? It would be great, but I thought Vector SDK custom programs do not communicate directly with Vector on local network. They would send commands to Anki Server and then Anki Server would relay the commands to registered Vector units -including RC programs. This may mean that SDK custom programs would also stop working when Anki Server shuts down. 
I hope I am wrong.

**Comment by RamblingGeekUK** [comment]
Hi Luke, 

I believe any talking Vector does and services like getting the time are all server driven from aws servers.

However the IP and products have been purchased by https://www.digitaldreamlabs.com/, I have reached out to them and it looks like they may do something with Vector but its very early days for them.

https://republic.co/digital-dream-labs-jacob-hanchar-digital-dream-labs-acquires-anki-this-is-huge-1

**Comment by CyrilPeponnet** [comment]
https://www.kickstarter.com/projects/anki/vector-by-anki-a-giant-roll-forward-for-robot-kind
