### ISSUE TITLE
No Anki account = no access to the SDK ever?

### ISSUE THREAD

**Issue by datto001** [anki/vector-python-sdk#29]
Even though I purchased a vector over the holidays (amazon), I never got around to making an Anki account with the company.  Because of that, I can't seem to authenticate (no username and password - never had one)

There still seems to be a fun of python programming to be had with this little guy...

**Comment by rmcolbert** [comment]
You should still be able to sign up from inside the Vector app.

**Comment by ali132-stack** [comment]
Hi guys , datto001 you can sign up in Anki.com , but the problem is with running SDK for Vector robot ... Can anyone of the authors support the SDK maintenance plz?! because we like Cozmo & Vector our Soul-Mates

**Comment by fndcz** [comment]
You can try to get the account from the Vector APP.

**Comment by sdevane** [comment]
December 19 2019 - I just bought a Vector and set it up todat. No problems creating the Anki Account and registering Vector (Android App & updating Vectors firmware). Linking Vector to Amazon Alexa also worked flawlessly. I can also confirm that the SDK examples worked fine too (just tested tutorial samples 01_.... -> 10... so far) - so ther doesn't seem to be any issues with Vector (to date at least).

**Comment by grant-olson** [comment]
You should be able to use the phone app now to create an account. An account is required to download the proper security certificates to talk to your robot. This is to prevent abusers from being able to take control or random robots. Once you have the certificate, you should no longer need to get anything from the Anki servers.

If you're worried about being unable to get the certificate in the future you should go through the initial configuration now, and then backup the contents of `~/.anki_vector` so that you will always have access to the robot.

Also note that performing a factory reset on the robot creates a new certificate, so you won't want to do that in the event it's impossible to log in to the anki servers in the future.

**Comment by Eddie7mail** [comment]
Is this on Vector Anki original app, or did you have a new App? 
    On Sunday, April 26, 2020, 10:15:50 PM GMT+1, Grant Olson <notifications@github.com> wrote:  
 
 


You should be able to use the phone app now to create an account. An account is required to download the proper security certificates to talk to your robot. This is to prevent abusers from being able to take control or random robots. Once you have the certificate, you should no longer need to get anything from the Anki servers.

If you're worried about being unable to get the certificate in the future you should go through the initial configuration now, and then backup the contents of ~/.anki_vector so that you will always have access to the robot.

Also note that performing a factory reset on the robot creates a new certificate, so you won't want to do that in the event it's impossible to log in to the anki servers in the future.

**Comment by grant-olson** [comment]
The existing Vector Anki app. Digital Dream Labs will eventually have a new version of the app that cuts over to our database servers. But for now the current app in the app store should work just fine.
